#!/usr/bin/env bash
# §M-INSTALL — Copy the precompiled helpers, skills and templates into place.
#
# The target machine needs Node and nothing else: no `npm install`, no lockfile,
# no toolchain. Everything under dist/ is dependency-free `.mjs`, so an install
# is a copy, and a copy is something a developer can inspect, diff and undo.
#
# Deliberately does not touch projects: no Git hooks, no per-project config, no
# version pin. A methodology that installs itself into a repository becomes that
# repository's problem to remove.

set -euo pipefail

SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PREFIX="${META_O_PREFIX:-$HOME/.local}"
SKILLS_DIR="${META_O_SKILLS_DIR:-$HOME/.claude/skills}"
INSTALL_SKILLS=1
RUN_SUITE=1
MODE="install"

usage() {
  cat <<'USAGE'
usage: install.sh [options]

  --prefix DIR        install binaries and libraries under DIR   (default: ~/.local)
  --skills-dir DIR    install the skills under DIR               (default: ~/.claude/skills)
  --no-skills         install only the CLI, libraries and templates
  --capability-suite  run the full backend capability suite afterwards  (default)
  --skip-suite        install without proving what the backend can do
  --help              show this message

Environment: META_O_PREFIX, META_O_SKILLS_DIR override the defaults.

Installs:
  PREFIX/lib/meta-o/            precompiled dependency-free .mjs helpers
  PREFIX/bin/meta-o             CLI entry point
  PREFIX/bin/meta-o-watchdog    watchdog entry point
  PREFIX/share/meta-o/templates project-owned QC starter templates
  SKILLS_DIR/<skill>/SKILL.md   the workflow skills

Touches no project: no hooks, no per-repository config, no version pin.
USAGE
}

while [ $# -gt 0 ]; do
  case "$1" in
    --prefix) PREFIX="$2"; shift 2 ;;
    --prefix=*) PREFIX="${1#*=}"; shift ;;
    --skills-dir) SKILLS_DIR="$2"; shift 2 ;;
    --skills-dir=*) SKILLS_DIR="${1#*=}"; shift ;;
    --no-skills) INSTALL_SKILLS=0; shift ;;
    --capability-suite) RUN_SUITE=1; shift ;;
    --skip-suite) RUN_SUITE=0; shift ;;
    --update) MODE="update"; shift ;;
    --help|-h) usage; exit 0 ;;
    *) printf 'unknown option: %s\n\n' "$1" >&2; usage >&2; exit 2 ;;
  esac
done

# --- preconditions -----------------------------------------------------------

if ! command -v node >/dev/null 2>&1; then
  printf 'node is required on this machine and was not found in PATH\n' >&2
  exit 1
fi

NODE_MAJOR="$(node --version | sed 's/^v\([0-9]*\).*/\1/')"
if [ "$NODE_MAJOR" -lt 22 ]; then
  printf 'node >= 22 is required; found %s\n' "$(node --version)" >&2
  exit 1
fi

# A missing dist/ in a source checkout is a build that has not happened yet, not
# a broken install: say so rather than copying an empty directory.
if [ ! -d "$SOURCE_DIR/dist" ]; then
  if [ -d "$SOURCE_DIR/node_modules" ]; then
    printf 'dist/ is missing; building it first\n'
    (cd "$SOURCE_DIR" && npm run --silent build)
  else
    printf 'dist/ is missing and node_modules/ is absent.\n' >&2
    printf 'Run `npm install && npm run build` in %s first.\n' "$SOURCE_DIR" >&2
    exit 1
  fi
fi

LIB_DIR="$PREFIX/lib/meta-o"
BIN_DIR="$PREFIX/bin"
SHARE_DIR="$PREFIX/share/meta-o"

printf '%s meta-o\n' "$([ "$MODE" = update ] && echo updating || echo installing)"
printf '  libraries : %s\n' "$LIB_DIR"
printf '  binaries  : %s\n' "$BIN_DIR"
printf '  templates : %s/templates\n' "$SHARE_DIR"
[ "$INSTALL_SKILLS" -eq 1 ] && printf '  skills    : %s\n' "$SKILLS_DIR"

# --- libraries ---------------------------------------------------------------

mkdir -p "$LIB_DIR" "$BIN_DIR" "$SHARE_DIR"

# Replace rather than merge: a stale module left behind by an older version is
# indistinguishable from a current one at runtime.
rm -rf "${LIB_DIR:?}/"*
(cd "$SOURCE_DIR/dist" && find . -name '*.mjs' -print0 | while IFS= read -r -d '' file; do
  mkdir -p "$LIB_DIR/$(dirname "$file")"
  cp "$file" "$LIB_DIR/$file"
done)

MJS_COUNT="$(find "$LIB_DIR" -name '*.mjs' | wc -l | tr -d ' ')"
if [ "$MJS_COUNT" -eq 0 ]; then
  printf 'no .mjs files were copied; the build output looks empty\n' >&2
  exit 1
fi

# --- entry points ------------------------------------------------------------

write_entry_point() {
  local name="$1" target="$2"
  cat > "$BIN_DIR/$name" <<EOF
#!/usr/bin/env bash
# Generated by meta-o install.sh. Safe to inspect, safe to delete.
exec node "$LIB_DIR/$target" "\$@"
EOF
  chmod 0755 "$BIN_DIR/$name"
}

write_entry_point meta-o cli/meta-o.mjs
write_entry_point meta-o-watchdog cli/watchdog-main.mjs

# --- templates ---------------------------------------------------------------

rm -rf "$SHARE_DIR/templates"
mkdir -p "$SHARE_DIR/templates"
cp -R "$SOURCE_DIR/templates/." "$SHARE_DIR/templates/"

# --- service units -----------------------------------------------------------

# Copied, never installed. §50 wants the watchdog run as a user service, and
# loading one is a change to the user's login session — their decision, made
# with the file in front of them. `meta-o watchdog enable` points here.
rm -rf "$SHARE_DIR/service"
mkdir -p "$SHARE_DIR/service"
cp "$SOURCE_DIR/service/meta-o-watchdog.service" "$SHARE_DIR/service/"
cp "$SOURCE_DIR/service/com.meta-o.watchdog.plist" "$SHARE_DIR/service/"

# --- skills ------------------------------------------------------------------

if [ "$INSTALL_SKILLS" -eq 1 ]; then
  mkdir -p "$SKILLS_DIR"
  for skill in "$SOURCE_DIR"/skills/*/; do
    [ -d "$skill" ] || continue
    name="$(basename "$skill")"
    rm -rf "${SKILLS_DIR:?}/$name"
    mkdir -p "$SKILLS_DIR/$name"
    cp -R "$skill." "$SKILLS_DIR/$name/"
    printf '  + skill %s\n' "$name"
  done
fi

# --- verification ------------------------------------------------------------

if ! "$BIN_DIR/meta-o" help >/dev/null; then
  printf 'the installed CLI does not run; refusing to report success\n' >&2
  exit 1
fi

printf 'installed %s helper module(s)\n' "$MJS_COUNT"

case ":$PATH:" in
  *":$BIN_DIR:"*) ;;
  *) printf 'note: %s is not in PATH\n' "$BIN_DIR" ;;
esac

# The suite runs by default because its *other* job is to record what the
# backend could do at install time. Without that record, preflight has nothing
# to compare a later, quieter degradation against, and the regression the whole
# mechanism exists to catch becomes invisible.
if [ "$RUN_SUITE" -eq 1 ]; then
  if ! command -v "${META_O_HERDR_BIN:-herdr}" >/dev/null 2>&1; then
    printf '\nnote: %s was not found, so the capability suite did not run.\n' "${META_O_HERDR_BIN:-herdr}"
    printf 'Run `meta-o capability-suite run --full` once the backend is installed;\n'
    printf 'until then preflight has no baseline to detect a regression against.\n'
  elif ! "$BIN_DIR/meta-o" capability-suite run --full --text; then
    printf '\nthe backend failed its capability suite.\n' >&2
    printf 'Preflight will refuse to start a run until this is fixed;\n' >&2
    printf 'there is deliberately no silent fallback.\n' >&2
    exit 1
  fi
fi

printf '\ndone. Next: `meta-o preflight` inside a project.\n'
