#!/usr/bin/env node
/**
 * §M-QC-BOOTSTRAP — Make an isolated checkout runnable before the gates start.
 *
 * Implements §A-AUTHORITATIVE-QC. `make qc` is the project's own gate and must
 * run wherever the candidate is checked out, which under §00 is never the
 * developer's working copy.
 *
 * §00 runs every gate in a fresh detached worktree of the candidate. A fresh
 * checkout is exactly that — the tracked tree and nothing else — so it has no
 * `node_modules` and no `dist`, and meta-o's own gates could not run inside the
 * isolation meta-o requires of everyone else. `make qc` there failed six gates
 * with `Cannot find module dist/cli/meta-o.mjs` and "this is not the tsc
 * command", which meant this project could not attest itself under its own
 * protocol.
 *
 * Tracking build output would have been the wrong fix: it puts generated bytes
 * inside the snapshot digest, so a rebuild would invalidate four attestations.
 * Instead `worktree run` exports `META_O_ORIGIN_REPO`, and this borrows the
 * dependencies from that checkout. Both directories are git-ignored, so nothing
 * the digest covers changes and the non-mutation check sees nothing.
 */

import { execFileSync } from "node:child_process";
import { existsSync, symlinkSync } from "node:fs";
import { join } from "node:path";

const repo = process.cwd();
const origin = process.env["META_O_ORIGIN_REPO"];
const done = [];

/** §M-QC-BOOTSTRAP — Report what was borrowed or built, then exit. */
function report(code) {
  process.stdout.write(`${done.length > 0 ? done.join("; ") : "nothing to do"}\n`);
  process.exit(code);
}

if (!existsSync(join(repo, "node_modules"))) {
  const borrowed = origin ? join(origin, "node_modules") : undefined;
  if (!borrowed || !existsSync(borrowed)) {
    process.stderr.write(
      "this checkout has no node_modules and no META_O_ORIGIN_REPO to borrow one from; " +
        "run `npm install` here, or launch the gate with `meta-o worktree run`\n",
    );
    report(1);
  }
  // A symlink rather than a copy: the dependency tree is large, the gate is
  // read-only against it, and a copy would make every gate run slower than the
  // gate itself.
  symlinkSync(borrowed, join(repo, "node_modules"), "junction");
  done.push(`borrowed node_modules from ${origin}`);
}

if (!existsSync(join(repo, "dist", "cli", "meta-o.mjs"))) {
  // Built here rather than borrowed: `dist` is the thing under test, and a gate
  // judging the origin checkout's build would be judging the wrong content.
  execFileSync("npx", ["--no-install", "tsc", "-p", "tsconfig.json"], {
    cwd: repo,
    stdio: "inherit",
  });
  done.push("built dist from this checkout's sources");
}

report(0);
